modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="olis_mod"
version="1.1.4"
displayName="Oli's Mod"
credits="oliik2013 first Minecraft mod"
displayURL="https://modrinth.com/mod/olis-mod"
logoFile="logo.png"
authors="oliik2013"
description='''
Cool new blocks and more!
'''

[[dependencies.olis_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




